services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
        - .:/app
  db:
    image: timescale/timescaledb-ha:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather_db
    expose:
      - 5432

volumes:
  postgres_data:
